name: tests

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        # Keep this in sync with tox.ini
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install tox
        run: |
          uv tool install --python ${{ matrix.python-version }} tox --with tox-gh --with tox-uv
      - name: Run tests
        run: tox
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}
